import { BaseAdapter } from './base.js';
import type { AgentId, DiagnosticResult } from '../types.js';
import { unlinkSync, existsSync } from 'fs';
import { join } from 'path';

export class AiderAdapter extends BaseAdapter {
  readonly agentId: AgentId = 'aider';
  readonly agentName = 'Aider';

  getOutputPaths(): string[] {
    const paths = ['.aider/instructions.md'];
    if (this.config.agents.aider?.config) {
      paths.push('.aider.conf.yml');
    }
    return paths;
  }

  compile(): Map<string, string> {
    const output = new Map<string, string>();

    // Instructions file
    let content = this.header();
    content += `# Aider Instructions\n\n`;
    content += `## Identity & Operating Mode\n\n`;
    content += `You are a **${this.config.identity.role}** — ${this.config.identity.description}\n\n`;
    content += `**Default operating posture:**\n${this.config.identity.posture}\n\n`;
    content += this.getMemoryProtocol() + '\n';

    for (const instruction of this.getInstructions()) {
      content += `## ${instruction.title}\n\n${instruction.content}\n\n`;
    }

    const extra = this.getAgentExtra();
    if (extra) {
      content += `## Additional Instructions\n\n${extra}\n\n`;
    }

    content += this.getSkillsSection() + '\n';
    content += this.getWorkspaceSection() + '\n';
    content += this.getPromptsSection();

    output.set('.aider/instructions.md', content.trimEnd() + '\n');

    // Optional YAML config
    const aiderConfig = this.config.agents.aider?.config;
    if (aiderConfig && Object.keys(aiderConfig).length > 0) {
      let yaml = '# AUTO-GENERATED by drevon — run `drevon sync` to regenerate\n';
      for (const [key, value] of Object.entries(aiderConfig)) {
        yaml += `${key}: ${JSON.stringify(value)}\n`;
      }
      output.set('.aider.conf.yml', yaml);
    }

    return output;
  }

  diagnose(dir: string): DiagnosticResult[] {
    return this.getOutputPaths().map((p) => this.checkFile(dir, p));
  }

  clean(dir: string): void {
    const instrPath = join(dir, '.aider', 'instructions.md');
    if (existsSync(instrPath)) unlinkSync(instrPath);
    const confPath = join(dir, '.aider.conf.yml');
    if (existsSync(confPath)) unlinkSync(confPath);
  }
}
