import type { DrevonConfig, AgentId, Instruction, DiagnosticResult } from '../types.js';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

export abstract class BaseAdapter {
  constructor(protected config: DrevonConfig) {}

  abstract readonly agentId: AgentId;
  abstract readonly agentName: string;

  abstract getOutputPaths(): string[];
  abstract compile(): Map<string, string>;
  abstract diagnose(dir: string): DiagnosticResult[];
  abstract clean(dir: string): void;

  protected header(): string {
    return (
      `<!-- AUTO-GENERATED by drevon v0.1.0 -->\n` +
      `<!-- Source: drevon.config.json -->\n` +
      `<!-- Do not edit directly — run \`drevon sync\` to regenerate. -->\n`
    );
  }

  protected getMemoryProtocol(): string {
    if (!this.config.memory.enabled) return '';

    const topicsTable =
      this.config.mode === 'hub'
        ? '| `topics/user.md` | User preferences, feedback, decisions |\n' +
          '| `topics/projects.md` | Registry of workspace projects |\n' +
          '| `topics/systems.md` | Systems & infrastructure |\n' +
          '| `topics/decisions/` | One file per significant decision |\n'
        : '| `topics/architecture.md` | Project context, structure, key files |\n' +
          '| `topics/patterns.md` | Code conventions, gotchas |\n' +
          '| `topics/decisions/` | One file per significant technical decision |\n';

    return (
      '## Memory Protocol\n\n' +
      'Persistent memory lives in `.drevon/memory/`, organized as an index plus lazily-loaded detail.\n\n' +
      '### Reading (cheap)\n' +
      '- **At session start, read only `.drevon/memory/INDEX.md`.** It carries the project summary, ' +
      'current focus, one-line pointers to every topic file, and the most recent log headlines.\n' +
      '- **Load a topic file only when it is relevant** to the task in front of you — the index tells ' +
      'you which one. Do **not** read the whole memory directory up front.\n' +
      '- To recall older history beyond the index, run `drevon memory search "<query>"`.\n\n' +
      '### Writing (via CLI — never hand-edit the log)\n' +
      'Use these commands so entries are appended cheaply and the index stays in sync. Never open the ' +
      '`log/` segments to edit them by hand.\n\n' +
      '| Command | Use when |\n' +
      '|---------|----------|\n' +
      '| `drevon memory log "<what happened>"` | After a significant action |\n' +
      '| `drevon memory decide "<title>" --why "<rationale>"` | A technical decision is made |\n' +
      '| `drevon memory learn "<insight>" --topic <patterns\\|architecture>` | A pattern/convention is discovered |\n' +
      '| `drevon memory note "<current focus>"` | The active-work focus changes |\n\n' +
      '### Topic files\n' +
      '| File | Contains |\n' +
      '|------|----------|\n' +
      topicsTable +
      '\n' +
      '### Self-evolution\n' +
      '- Record learnings as you go, but keep it lean — the index is budget-capped for a reason.\n' +
      '- If you repeat a multi-step workflow, save it as a reusable prompt in `.drevon/prompts/`.\n' +
      '- Run `drevon memory compact` periodically to keep memory small and fast.\n'
    );
  }

  protected getInstructions(): Instruction[] {
    return this.config.instructions || [];
  }

  protected getSkillsSection(): string {
    if (!this.config.skills.enabled) return '';

    let content = '## Installed Skills\n\n';
    content += '> **IMPORTANT:** To install new skills, always use `drevon skill add <source>` — do NOT use `npx skills add` directly.\n';
    content += '> Drevon tracks skills in `.drevon/skills/` and keeps all agent configs in sync.\n\n';

    // Read actual installed skills from lock file
    const lockPath = join(process.cwd(), 'skills-lock.json');
    let installedSkills: { name: string; description: string }[] = [];
    if (existsSync(lockPath)) {
      try {
        const data = JSON.parse(readFileSync(lockPath, 'utf-8'));
        if (Array.isArray(data.skills)) {
          installedSkills = data.skills;
        }
      } catch {
        // ignore parse errors
      }
    }

    if (installedSkills.length > 0) {
      content += '| Skill | Description |\n';
      content += '|-------|-------------|\n';
      for (const s of installedSkills) {
        content += `| \`${s.name}\` | ${s.description || '—'} |\n`;
      }
      content += '\n';
      content += 'Read each skill\'s SKILL.md in `.drevon/skills/<name>/` for detailed usage instructions.\n';
    } else {
      content += 'No skills installed yet. Install with: `drevon skill add <owner/repo/skill-name>`\n';
    }

    return content;
  }

  protected getWorkspaceSection(): string {
    if (!this.config.workspace.enabled) return '';
    let content = `## Workspace Organization\n\nAll work happens inside \`${this.config.workspace.directory}/\`.\n`;
    if (this.config.workspace.rules?.length) {
      content += '\n### Rules\n';
      for (const rule of this.config.workspace.rules) {
        content += `- ${rule}\n`;
      }
    }
    return content;
  }

  protected getPromptsSection(): string {
    if (!this.config.prompts.enabled) return '';
    return (
      '## Prompts\n\n' +
      'Reusable workflow templates live in `.drevon/prompts/`.\n' +
      '- Before starting a complex task, check if a relevant prompt exists\n' +
      '- When you complete a novel multi-step workflow, save it as a prompt\n' +
      '- Format: markdown with YAML frontmatter (title, description, tags)\n'
    );
  }

  protected getAgentExtra(): string {
    const agentConfig = this.config.agents[this.agentId];
    return agentConfig?.extraInstructions || '';
  }

  protected checkFile(dir: string, relativePath: string): DiagnosticResult {
    const fullPath = join(dir, relativePath);
    if (!existsSync(fullPath)) {
      return { file: relativePath, status: 'missing', message: 'File does not exist' };
    }
    return { file: relativePath, status: 'ok', message: 'File exists' };
  }
}
