import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { createDefaultConfig } from '../../src/core/config.js';
import { CopilotAdapter } from '../../src/adapters/copilot.js';
import { ClaudeCodeAdapter } from '../../src/adapters/claude.js';
import { CursorAdapter } from '../../src/adapters/cursor.js';
import { CodexAdapter } from '../../src/adapters/codex.js';
import { WindsurfAdapter } from '../../src/adapters/windsurf.js';
import { ClineAdapter } from '../../src/adapters/cline.js';
import { AiderAdapter } from '../../src/adapters/aider.js';
import { ContinueAdapter } from '../../src/adapters/continue.js';
import { GeminiAdapter } from '../../src/adapters/gemini.js';
import { AntigravityAdapter } from '../../src/adapters/antigravity.js';
import type { DrevonConfig } from '../../src/types.js';

function makeConfig(mode: 'hub' | 'project' = 'hub'): DrevonConfig {
  return createDefaultConfig(mode, 'test', {
    role: 'test-role',
    description: 'Test agent for testing',
    posture: 'Be thorough and test everything',
    capabilities: ['engineering'],
  }, ['copilot', 'claude', 'cursor', 'codex', 'windsurf', 'cline', 'aider', 'continue', 'gemini', 'antigravity']);
}

describe('CopilotAdapter', () => {
  it('generates copilot-instructions.md', () => {
    const config = makeConfig();
    const adapter = new CopilotAdapter(config);
    const output = adapter.compile();

    expect(output.has('.github/copilot-instructions.md')).toBe(true);
    const content = output.get('.github/copilot-instructions.md')!;
    expect(content).toContain('AUTO-GENERATED by drevon');
    expect(content).toContain('# Copilot Instructions');
    expect(content).toContain('test-role');
    expect(content).toContain('Memory Protocol');
  });
});

describe('ClaudeCodeAdapter', () => {
  it('generates CLAUDE.md with allowed commands', () => {
    const config = makeConfig();
    const adapter = new ClaudeCodeAdapter(config);
    const output = adapter.compile();

    expect(output.has('CLAUDE.md')).toBe(true);
    const content = output.get('CLAUDE.md')!;
    expect(content).toContain('CLAUDE.md');
    expect(content).toContain('Allowed Commands');
    expect(content).toContain('`git`');
  });
});

describe('CursorAdapter', () => {
  it('generates multiple .mdc files', () => {
    const config = makeConfig();
    const adapter = new CursorAdapter(config);
    const output = adapter.compile();

    expect(output.has('.cursor/rules/core.mdc')).toBe(true);
    expect(output.has('.cursor/rules/memory.mdc')).toBe(true);

    const core = output.get('.cursor/rules/core.mdc')!;
    expect(core).toContain('alwaysApply: true');
    expect(core).toContain('test-role');
  });
});

describe('CodexAdapter', () => {
  it('generates AGENTS.md', () => {
    const config = makeConfig();
    const adapter = new CodexAdapter(config);
    const output = adapter.compile();

    expect(output.has('AGENTS.md')).toBe(true);
    const content = output.get('AGENTS.md')!;
    expect(content).toContain('AGENTS.md');
    expect(content).toContain('Memory Protocol');
  });
});

describe('WindsurfAdapter', () => {
  it('generates .windsurfrules', () => {
    const config = makeConfig();
    const adapter = new WindsurfAdapter(config);
    const output = adapter.compile();

    expect(output.has('.windsurfrules')).toBe(true);
    const content = output.get('.windsurfrules')!;
    expect(content).toContain('Windsurf Rules');
  });
});

describe('ClineAdapter', () => {
  it('generates .clinerules', () => {
    const config = makeConfig();
    const adapter = new ClineAdapter(config);
    const output = adapter.compile();

    expect(output.has('.clinerules')).toBe(true);
    const content = output.get('.clinerules')!;
    expect(content).toContain('Cline Rules');
  });
});

describe('AiderAdapter', () => {
  it('generates .aider/instructions.md', () => {
    const config = makeConfig();
    const adapter = new AiderAdapter(config);
    const output = adapter.compile();

    expect(output.has('.aider/instructions.md')).toBe(true);
    const content = output.get('.aider/instructions.md')!;
    expect(content).toContain('Aider Instructions');
  });
});

describe('ContinueAdapter', () => {
  it('generates .continue/rules/drevon.md', () => {
    const config = makeConfig();
    const adapter = new ContinueAdapter(config);
    const output = adapter.compile();

    expect(output.has('.continue/rules/drevon.md')).toBe(true);
    const content = output.get('.continue/rules/drevon.md')!;
    expect(content).toContain('Continue.dev Rules');
  });
});

describe('AntigravityAdapter', () => {
  it('generates AGENTS.md at the project root — the convention shared with codex', () => {
    const config = makeConfig();
    const adapter = new AntigravityAdapter(config);
    const output = adapter.compile();

    expect(adapter.getOutputPaths()).toEqual(['AGENTS.md']);
    const content = output.get('AGENTS.md')!;
    expect(content).toContain('AUTO-GENERATED by drevon');
    expect(content).toContain('# AGENTS.md');
    expect(content).toContain('test-role');
    expect(content).toContain('Memory Protocol');
  });

  it('is idempotent — compiling twice yields identical output', () => {
    const adapter = new AntigravityAdapter(makeConfig());
    expect(adapter.compile().get('AGENTS.md')).toBe(adapter.compile().get('AGENTS.md'));
  });
});

describe('GeminiAdapter', () => {
  it('generates GEMINI.md at the project root', () => {
    const config = makeConfig();
    const adapter = new GeminiAdapter(config);
    const output = adapter.compile();

    expect(adapter.getOutputPaths()).toEqual(['GEMINI.md']);
    expect(output.has('GEMINI.md')).toBe(true);
    const content = output.get('GEMINI.md')!;
    expect(content).toContain('AUTO-GENERATED by drevon');
    expect(content).toContain('# GEMINI.md');
    expect(content).toContain('test-role');
    expect(content).toContain('Memory Protocol');
  });

  it('renders the installed-skills table from skills-lock.json', () => {
    const dir = mkdtempSync(join(tmpdir(), 'drevon-gemini-'));
    const prevCwd = process.cwd();
    try {
      writeFileSync(
        join(dir, 'skills-lock.json'),
        JSON.stringify({ skills: [{ name: 'find-skills', description: 'Discover skills' }] }),
      );
      process.chdir(dir);

      const content = new GeminiAdapter(makeConfig()).compile().get('GEMINI.md')!;
      expect(content).toContain('## Installed Skills');
      expect(content).toContain('| Skill | Description |');
      expect(content).toContain('| `find-skills` | Discover skills |');
    } finally {
      process.chdir(prevCwd);
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it('is idempotent across re-syncs', () => {
    const config = makeConfig();
    const first = new GeminiAdapter(config).compile().get('GEMINI.md')!;
    const second = new GeminiAdapter(config).compile().get('GEMINI.md')!;
    expect(second).toBe(first);
  });
});

describe('Hub vs Project mode', () => {
  it('hub mode includes workspace section', () => {
    const config = makeConfig('hub');
    const adapter = new CopilotAdapter(config);
    const output = adapter.compile();
    const content = output.get('.github/copilot-instructions.md')!;
    expect(content).toContain('Workspace Organization');
  });

  it('project mode does not include workspace section', () => {
    const config = makeConfig('project');
    const adapter = new CopilotAdapter(config);
    const output = adapter.compile();
    const content = output.get('.github/copilot-instructions.md')!;
    expect(content).not.toContain('Workspace Organization');
  });

  it('hub mode references hub topic files and the v2 index protocol', () => {
    const config = makeConfig('hub');
    const adapter = new CopilotAdapter(config);
    const output = adapter.compile();
    const content = output.get('.github/copilot-instructions.md')!;
    expect(content).toContain('INDEX.md');
    expect(content).toContain('topics/user.md');
  });

  it('project mode references project topic files and the v2 index protocol', () => {
    const config = makeConfig('project');
    const adapter = new CopilotAdapter(config);
    const output = adapter.compile();
    const content = output.get('.github/copilot-instructions.md')!;
    expect(content).toContain('INDEX.md');
    expect(content).toContain('topics/architecture.md');
  });

  it('no longer instructs agents to read all memory files eagerly', () => {
    const content = new CopilotAdapter(makeConfig('project')).compile().get('.github/copilot-instructions.md')!;
    expect(content).not.toContain('Read all memory files at the start of every session');
  });
});
